<?php

namespace App\Filament\Resources\Reports\Pages;

use App\Filament\Resources\Reports\ReportResource;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Contracts\Support\Htmlable;

class ListReports extends ListRecords
{
    protected static string $resource = ReportResource::class;

    public function getSubheading(): string|Htmlable|null
    {
        return 'Log of all PDF, CSV, and ZIP exports generated by users. '
            .'Each entry records who exported, which sheet, and when.';
    }
}
